module.exports = [
  {
    slug: 'lankacart-commerce-suite',
    name: 'LankaCart Commerce Suite',
    type: 'E-commerce Platform',
    summary: 'Multi-vendor storefront with integrated order, payment, and inventory workflows for fast-growing retailers.',
    stack: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    results: ['42% faster checkout', '2.4x repeat orders'],
    color: 'from-blue-600 to-cyan-500',
    image: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80',
    order: 1,
    active: true,
  },
  {
    slug: 'medflow-clinic-portal',
    name: 'MedFlow Clinic Portal',
    type: 'Healthcare Management',
    summary: 'Centralized patient records, appointment orchestration, and doctor dashboards with role-based access.',
    stack: ['React', 'Express', 'PostgreSQL', 'Redis'],
    results: ['60% lower admin time', '99.9% uptime'],
    color: 'from-cyan-600 to-teal-500',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80',
    order: 2,
    active: true,
  },
  {
    slug: 'fleettrack-analytics',
    name: 'FleetTrack Analytics',
    type: 'Logistics Dashboard',
    summary: 'Live route monitoring and predictive delivery insights to optimize last-mile operations.',
    stack: ['Next.js', 'NestJS', 'Kafka', 'TimescaleDB'],
    results: ['31% fuel savings', '28% faster delivery ETA'],
    color: 'from-indigo-600 to-blue-500',
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
    order: 3,
    active: true,
  },
  {
    slug: 'learnedge-lms',
    name: 'LearnEdge LMS',
    type: 'Education Platform',
    summary: 'Learning platform with instructor workflows, assessments, and progress analytics for private institutes.',
    stack: ['React', 'Node.js', 'MongoDB', 'AWS S3'],
    results: ['3x course completion', '18k active learners'],
    color: 'from-sky-600 to-blue-500',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    order: 4,
    active: true,
  },
  {
    slug: 'buildops-erp-lite',
    name: 'BuildOps ERP Lite',
    type: 'Construction Operations',
    summary: 'Project budgeting, procurement tracking, and workforce scheduling for mid-size construction teams.',
    stack: ['Vue', 'Laravel', 'MySQL', 'Docker'],
    results: ['25% cost leakage reduction', '40% faster reporting'],
    color: 'from-blue-700 to-indigo-600',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
    order: 5,
    active: true,
  },
  {
    slug: 'travelcore-booking-hub',
    name: 'TravelCore Booking Hub',
    type: 'Travel Reservation App',
    summary: 'Unified booking flow with package builder, payment gateway, and partner management tools.',
    stack: ['React', 'Express', 'MongoDB', 'Cloudinary'],
    results: ['2.1x conversion growth', '35% fewer support tickets'],
    color: 'from-cyan-500 to-blue-600',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    order: 6,
    active: true,
  }
];